<?php
// user/music.php
session_start();

// Set current page as hightlighted in sidebar
$current_page = 'about';

// Get user data
if (!isset($user) && isset($_SESSION['user_id'])) {
    require_once '../user/db_connect.php';
    $user_id = $_SESSION['user_id'];
    $sql = "SELECT user_id, username, email, full_name, role FROM users WHERE user_id = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $user = $result->fetch_assoc();
}




?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crow Education - Music Player</title>
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="../css/music.css">
    <link rel="stylesheet" href="../css/header.css">
    <link rel="stylesheet" href="../css/sidebar.css">
</head>
<!-- Theme Selector - Index 版本 -->
<div class="theme-selector" id="themeSelector">
    <div class="theme-options-grid">
        <div class="theme-option theme-1 active" data-theme="1"></div>
        <div class="theme-option theme-2" data-theme="2"></div>
        <div class="theme-option theme-3" data-theme="3"></div>
        <div class="theme-option theme-4" data-theme="4"></div>
        <div class="theme-option theme-5" data-theme="5"></div>
    </div>

    <!-- Auto Theme Toggle inside Theme Selector -->
    <div class="auto-theme-section" id="autoThemeSection">
        <div class="auto-theme-info">
            <i class="fas fa-sync-alt"></i>
            <span>Auto Theme</span>
        </div>
        <div class="auto-theme-status"></div>
    </div>
</div>
<body>
    <!-- Header Container -->
    <div id="header-container"></div>

    <!-- Page Container -->
    <div class="page-container">
        <!-- Sidebar Component -->
<div id="sidebar-container"></div>
    
    <!-- Main Content Area -->
    <main class="main-content" id="main-content">
    <div class="floating-elements"></div>
    
    <main class="content">
        <!-- Music module -->
        <div class="music-page">
            <!-- left playlists -->
            <aside class="library">
                <h3>Your Playlists</h3>
                <div id="playlistsContainer">
                    <!-- Playlists will be dynamically generated here -->
                </div>
            </aside>

            <!-- right: playlist & player -->
            <section class="playlist-area">
                <div class="top-controls">
                    <div>
                        <h2 style="margin:0 0 6px 0" id="currentPlaylistName">Focus Playlist</h2>
                        <div style="color:var(--gray); font-size:13px" id="currentPlaylistDescription">A collection
                            of focus-enhancing tracks</div>
                    </div>

                    <div style="display:flex; gap:10px; align-items:center;">
                        <div class="tabs">
                            <div class="tab active" id="tabAll">All Songs</div>
                            <div class="tab" id="tabFavs">Favorites</div>
                        </div>

                        <div class="playlist-search">
                            <i class="fas fa-search" style="color:var(--gray)"></i>
                            <input id="searchInput" placeholder="Search songs, artists..." />
                        </div>

                        <button class="control-btn" id="shuffleBtn" title="Shuffle"><i
                                class="fas fa-random"></i></button>
                        <button class="control-btn" id="likeAllBtn" title="Like all"><i
                                class="fas fa-heart"></i></button>
                    </div>
                </div>

                <!-- tracks -->
                <div>
                    <table class="tracks-table" aria-hidden="false">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Artist</th>
                                <th style="text-align:right;padding-right:12px">Duration</th>
                            </tr>
                        </thead>
                        <tbody id="tracksBody">
                            <!-- generated by JS -->
                        </tbody>
                    </table>
                </div>

                <!-- invisible audio element used to load metadata when selecting -->
                <audio id="audio" preload="metadata"></audio>
            </section>
        </div>
    </main>

    <!-- global player bar (always visible) -->
    <div class="player-bar" id="playerBar" style="display:flex;">
        <img src="" alt="cover" class="player-cover" id="playerCover">
        <div class="player-meta">
            <div class="title" id="playerTitle">Not playing</div>
            <div class="artist" id="playerArtist">—</div>
        </div>

        <div style="display:flex; flex-direction:column; gap:8px; align-items:center; flex:1;">
            <div class="player-controls">
                <button class="control-btn" id="prevTrack"><i class="fas fa-backward"></i></button>
                <button class="control-btn" id="playPauseMain"><i class="fas fa-play"></i></button>
                <button class="control-btn" id="nextTrack"><i class="fas fa-forward"></i></button>
                <!-- Loop button -->
                <button class="control-btn" id="loopBtn" title="Loop"><i class="fas fa-redo"></i></button>
            </div>

            <div class="progress-wrap">
                <div class="progress" id="progressBar">
                    <div class="progress-fill" id="progressFill"></div>
                </div>
                <div class="time-row"><span id="currentTime">0:00</span><span id="totalTime">0:00</span></div>
            </div>
        </div>

        <div style="display:flex; align-items:center; gap:12px;">
            <div class="volume">
                <i class="fas fa-volume-up" style="color:var(--gray)"></i>
                <input id="volumeRange" type="range" min="0" max="1" step="0.01" value="0.8">
            </div>
            <button class="control-btn" id="queueBtn" title="Queue"><i class="fas fa-list"></i></button>
        </div>
    </div>

    <!-- Page Footer -->
    <div id="footer-container"></div>

    <script src="../js/music.js"></script>
    <script src="../js/sidebar.js"></script>

</body>

</html>