<?php
// user/schedule.php
session_start();

// Set current page as hightlighted in sidebar
$current_page = 'about';

// Get user data
if (!isset($user) && isset($_SESSION['user_id'])) {
    require_once '../user/db_connect.php';
    $user_id = $_SESSION['user_id'];
    $sql = "SELECT user_id, username, email, full_name, role FROM users WHERE user_id = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $user = $result->fetch_assoc();
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crow Education - Schedule</title>
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <link rel="stylesheet" href="../css/schedule.css">
    <link rel="stylesheet" href="../css/header.css">
    <link rel="stylesheet" href="../css/sidebar.css">
 </head>
<!-- Theme Selector - Index 版本 -->
<div class="theme-selector" id="themeSelector">
    <div class="theme-options-grid">
        <div class="theme-option theme-1 active" data-theme="1"></div>
        <div class="theme-option theme-2" data-theme="2"></div>
        <div class="theme-option theme-3" data-theme="3"></div>
        <div class="theme-option theme-4" data-theme="4"></div>
        <div class="theme-option theme-5" data-theme="5"></div>
    </div>

    <!-- Auto Theme Toggle inside Theme Selector -->
    <div class="auto-theme-section" id="autoThemeSection">
        <div class="auto-theme-info">
            <i class="fas fa-sync-alt"></i>
            <span>Auto Theme</span>
        </div>
        <div class="auto-theme-status"></div>
    </div>
</div>
<body>
    <!-- Header Container -->
    <div id="header-container"></div>

    <!-- Page Container -->
    <div class="page-container">
        <!-- Sidebar Component -->
<div id="sidebar-container"></div>
    
    <!-- Main Content Area -->
    <main class="main-content" id="main-content">
    <div class="floating-elements"></div>
    
    <div class="schedule-container" id="scheduleModule">
        <div class="schedule-header">
            <h2 class="schedule-title">
                <i class="fas fa-calendar-alt"></i>
                My Schedule
            </h2>
            <div class="schedule-controls">
                <button class="schedule-btn" id="createEventBtn">
                    <i class="fas fa-plus"></i> Create Event
                </button>
                <button class="schedule-btn" id="todayBtn">
                    <i class="fas fa-calendar-day"></i> Today
                </button>
            </div>
        </div>

        <div class="calendar-container">
            <div class="calendar-header">
                <div class="calendar-nav">
                    <button class="nav-btn" id="prevBtn">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <div class="current-period" id="currentPeriod">November 2023</div>
                    <button class="nav-btn" id="nextBtn">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
                <div class="calendar-view">
                    <button class="view-btn active" data-view="month">Month</button>
                    <button class="view-btn" data-view="week">Week</button>
                    <button class="view-btn" data-view="day">Day</button>
                </div>
            </div>

            <!-- Month View -->
            <div class="calendar-grid" id="monthView">
                <!-- Month view will be generated by JavaScript -->
            </div>

            <!-- Week View -->
            <div class="week-view" id="weekView">
                <div class="week-header">
                    <div class="week-time-label">Time</div>
                    <!-- Week day headers will be generated by JavaScript -->
                </div>
                <div class="week-grid" id="weekGrid">
                    <!-- Week grid will be generated by JavaScript -->
                </div>
            </div>

            <!-- Day View -->
            <div class="day-view" id="dayView">
                <div class="day-header">
                    <div class="day-title" id="dayTitle">Monday, November 27, 2023</div>
                </div>
                <div class="day-grid" id="dayGrid">
                    <!-- Day grid will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Event Modal -->
    <div class="modal-overlay" id="eventModal">
        <div class="event-modal">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle">Create New Event</h3>
                <button class="close-modal" id="closeModal">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="form-label" for="eventTitle">Event Title</label>
                    <input type="text" class="form-input" id="eventTitle" placeholder="Add title">
                </div>
                <div class="form-group">
                    <label class="form-label" for="eventDate">Date</label>
                    <input type="date" class="form-input" id="eventDate">
                </div>
                <div class="form-group">
                    <label class="form-label" for="eventTime">Time</label>
                    <input type="time" class="form-input" id="eventTime">
                </div>
                <div class="form-group">
                    <label class="form-label" for="eventDescription">Description</label>
                    <textarea class="form-input" id="eventDescription" rows="3"
                        placeholder="Add description"></textarea>
                </div>
                <div class="form-group">
                    <label class="form-label">Event Type</label>
                    <div class="color-options">
                        <div class="color-option active" style="background-color: #3498db;" data-color="default"
                            data-type="default"></div>
                        <div class="color-option" style="background-color: #FF6B6B;" data-color="personal"
                            data-type="personal"></div>
                        <div class="color-option" style="background-color: #4ECDC4;" data-color="work" data-type="work">
                        </div>
                        <div class="color-option" style="background-color: #FFE66D;" data-color="study"
                            data-type="study"></div>
                        <div class="color-option" style="background-color: #6A0572;" data-color="meeting"
                            data-type="meeting"></div>
                        <div class="color-option" style="background-color: #1A535C;" data-color="exam" data-type="exam">
                        </div>
                        <div class="color-option" style="background-color: #FF9A8B;" data-color="assignment"
                            data-type="assignment"></div>
                        <div class="color-option" style="background-color: #292F36;" data-color="other"
                            data-type="other"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-cancel" id="cancelEvent">Cancel</button>
                <button class="btn btn-delete" id="deleteEvent" style="display: none;">Delete</button>
                <button class="btn btn-save" id="saveEvent">Save</button>
            </div>
        </div>
    </div>

    <!-- Page Footer -->
    <div id="footer-container"></div>


    <script src="../js/schedule.js"></script>
    <script src="../js/sidebar.js"></script>
</body>

</html>